In [1]:
import tensorflow as tf
print(tf.__version__)

1.13.1


In [6]:
# variables in tf <=> tensors

# by default, TF supposes two steps computational grpah building and execution
# execution graph - directional graph of operations wiht tensors
# session - execution of graph


# summaries
# tensorboard

In [35]:
# Create variables with exact values

tf.reset_default_graph()

v1 = tf.Variable([1,2,3,4,5], name='v1')
v2 = tf.Variable([1,2,3,4,5], name='v2')

v3 = tf.add(v1, v2, name="add")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    vo3 = sess.run(v3)
    print(vo3)

[ 2  4  6  8 10]


In [37]:
# create multidimentional variables (tensors)

tf.reset_default_graph()

v4 = tf.ones([2,3], name='v4')
v5 = tf.zeros([2,3], name='v5')

#TODO: you may try random initializers: tf.random.random_normal, ....  

v6 = tf.add(v4, v5, name="add_ones")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    vo4, vo5, vo6 = sess.run([v4, v5, v6])
    print('vo4\n', vo4)
    print('vo5\n', vo5)
    print('vo6\n', vo6)

vo4
 [[1. 1. 1.]
 [1. 1. 1.]]
vo5
 [[0. 0. 0.]
 [0. 0. 0.]]
vo6
 [[1. 1. 1.]
 [1. 1. 1.]]


In [64]:
# get shape

tf.reset_default_graph()

v4 = tf.ones([2,3], name='v4')
v5 = tf.zeros([2,3], name='v5')

v6 = tf.add(v4, v5, name="add_ones")

print(v4.get_shape().as_list())  # return list with dimensions
print(tf.shape(v4))              # return tensor

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    vo4, vo5, vo6 = sess.run([v4, v5, v6])
    print('vo4\n', vo4)
    print('vo5\n', vo5)
    print('vo6\n', vo6)

[2, 3]
Tensor("Shape:0", shape=(2,), dtype=int32)
vo4
 [[1. 1. 1.]
 [1. 1. 1.]]
vo5
 [[0. 0. 0.]
 [0. 0. 0.]]
vo6
 [[1. 1. 1.]
 [1. 1. 1.]]


In [81]:
# placeholder and values feeding
tf.reset_default_graph()

v_input = tf.placeholder(tf.int32, [], name='v_input')

v1 = tf.Variable([1,2,3,4,5], name='v1')

v2 = tf.multiply(v1, v_input, name="v2")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        v  = sess.run(v2, feed_dict={v_input: i+1})
        print(v)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 3  6  9 12 15]
[ 4  8 12 16 20]
[ 5 10 15 20 25]


In [80]:
# placeholder and values feeding
tf.reset_default_graph()

v_input = tf.placeholder(tf.int32, [], name='v_input')

v1 = tf.Variable([1,2,3,4,5], name='v1')

v2 = tf.multiply(v1, v_input, name="v2")

assign_op = tf.assign(v1, v2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        v, a  = sess.run([v2, assign_op], feed_dict={v_input: i+1})
        print(v)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 6 12 18 24 30]
[ 24  48  72  96 120]
[120 240 360 480 600]


In [ ]:
# placeholder and values feeding
tf.reset_default_graph()

v_input = tf.placeholder(tf.int32, [], name='v_input')

v1 = tf.Variable([1,2,3,4,5], name='v1')

v2 = tf.multiply(v1, v_input, name="v2")

assign_op = tf.assign(v1, v2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        v, _  = sess.run([v2, assign_op], feed_dict={v_input: i+1})
        print(v)

In [2]:
# tensorboard

tf.reset_default_graph()

v_input = tf.placeholder(tf.int32, [], name='v_input')

v1 = tf.Variable([1,2,3,4,5], name='v1')
v2 = tf.Variable([1,2,3,4,5], name='v2')

v3 = v_input * tf.add(v1, v2, name="add")

assign_op = tf.assign(v1, v3)

tf.summary.scalar('v_input', v_input)

tf.summary.histogram('v1', v1)
tf.summary.histogram('v2', v2)
tf.summary.histogram('v3', v3)

merged_summaries = tf.summary.merge_all()

with tf.Session() as sess:
    writer = tf.summary.FileWriter('log', sess.graph)

    sess.run(tf.global_variables_initializer())
    
    for i in range(5):
        v, summs  = sess.run([assign_op, merged_summaries], feed_dict={v_input: i+1})
        print(v)
        writer.add_summary(summs, global_step=i)


Instructions for updating:
Colocations handled automatically by placer.
[ 2  4  6  8 10]
[ 6 12 18 24 30]
[ 21  42  63  84 105]
[ 88 176 264 352 440]
[ 445  890 1335 1780 2225]
